













document.addEventListener('contextmenu', event => event.preventDefault());




// #Background Sounds
//var audio = new Audio("Sounds/Whitespace.mp3");
//
//audio.oncanplaythrough = function(){
//audio.play();
//}
//s
//audio.loop = true;
//setTimeout(()=>{audio.play()},2000);



































































































































// #Title

//let a=Math.random()
//if(a<1){
//    setTimeout(()=>{document.title="Oh Hey, uhh."},2000);
//    setTimeout(()=>{document.title="this is an easter egg"},4000);
//    setTimeout(()=>{document.title="that the title changes."},6000);
//    setTimeout(()=>{document.title="can we talk? pls?"},8000);
//    setTimeout(()=>{document.title="i wanna open up."},10000);
//    setTimeout(()=>{document.title="About Who i like."},12000);
//    setTimeout(()=>{document.title="Her name's Stefany."},14000);
//    setTimeout(()=>{document.title="I Have liked her since..."},16000);
//    setTimeout(()=>{document.title="Since 8th grade."},18000);
//}

